name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    - uses: getgauge/setup-gauge@master
      with:
        gauge-version: '1.5.4'
        gauge-plugins: java, html-report
    - name: Build with Gradle on ubuntu
      if: matrix.os != 'windows-latest'
      run: |
        ./gradlew plugin:build
        ./gradlew gaugeNewDevRepeat --warning-mode all
    - name: Build with Gradle on windows
      if: matrix.os == 'windows-latest'
      run: .\gradlew.bat plugin:check build