name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    - uses: getgauge/setup-gauge@master
      with:
        gauge-version: 'master'
    - uses: gradle/gradle-build-action@v2
    - name: Build with Gradle on ubuntu
      if: matrix.os != 'windows-latest'
      run: ./gradlew plugin:build gaugeValidate gaugeDevRepeat
    - name: Build with Gradle on windows
      if: matrix.os == 'windows-latest'
      run: |
        gauge.exe -v
        cd sample && gauge.exe install
        gradle gaugeExec