name: Release on PR Merge

on: deployment

jobs:
  deploy:
    if: github.event.deployment.environment == 'production'
    name: Deploy to gradle portal
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      GRADLE_PUBLISHKEY: '${{ secrets.GRADLE_PUBLISHKEY }}'
      GRADLE_SECRET: '${{ secrets.GRADLE_SECRET }}'
    steps:
      - uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build artifacts
        run: |
          ./gradlew clean build
      - name: Upload to gradle portal
        run: |
          ./gradlew publishPlugins -Pgradle.publish.key=$GRADLE_PUBLISHKEY -Pgradle.publish.secret=$GRADLE_SECRET